name: 'Divine Dreams & Destiny'
favicon: null
layout_spectrum: 0.970820716349408
typography_spectrum: 0.7157993502914906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9570793409366161
  lightness: 0.29570149164646864
  saturation: 0.7356353150680661
  rhythmicContrast: 0.42211735993623734
purpose: []
